version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      kubernetes-stack:
        patterns:
          - "io.fabric8*"
          - "io.javaoperatorsdk*"
      observability:
        patterns:
          - "io.micrometer*"
          - "ch.qos.logback*"
          - "net.logstash.logback*"
      kotlin-and-build:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.diffplug.spotless"
      runtime-support:
        patterns:
          - "com.sksamuel.hoplite*"
          - "com.fasterxml.jackson.module*"
          - "org.http4k*"
          - "io.insert-koin*"
      testing:
        patterns:
          - "io.mockk*"
          - "org.awaitility*"
          - "org.testcontainers*"
          - "io.github.hakky54:logcaptor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker:
        patterns:
          - '*'
