apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: test-namespace
  labels:
    app.kubernetes.io/name: flais-test-application
    app.kubernetes.io/instance: flais-test-application_test-com
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: test-application
    app.kubernetes.io/part-of: flais
    fintlabs.no/team: flais
spec:
  org-id: test.com

  replicas: 1
  port: 80
  image: docker/getting-started
  resources:
    limits:
      memory: "256Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  probes:
    startup:
      path: /startup
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
    readiness:
      path: /readiness
      port: 8080
      initialDelaySeconds: 0
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3
    liveness:
      path: /liveness
      port: 8080
      initialDelaySeconds: 20
      failureThreshold: 5
      periodSeconds: 10
      timeoutSeconds: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  observability:
    metrics:
      path: /metrics
      port: 8080
    logging:
      loki: true

  env:
    - name: ENV1
      value: test
    - name: ENV2
      value: test
    - name: ENV3
      value: test
  envFrom:
    - secretRef:
        name: flais-test-application-secret
    - configMapRef:
        name: flais-test-application-configmap
  onePassword:
    itemPath: "vaults/aks-alpha-vault/items/azurerator"
  database:
    database: test
  kafka:
    acls:
      - topic: '*.test.topic'
        permission: read

  ingress:
    routes:
      - host: flais-test-application.example.com
        path: /test
        headers:
          x-forwarded: flais-test-application.example.com
          x-forwarded-path: re:^test(.*)$
        queries:
          showAll: false
      - host: flais-test-application.example.com
        path: /team/{name:[a-z]+}
        middlewares:
          - some-middleware
    middlewares:
      - another-middleware