apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: test-namespace
  labels:
    app.kubernetes.io/name: flais-test-application
    app.kubernetes.io/instance: flais-test-application_test-com
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: test-application
    app.kubernetes.io/part-of: flais
    fintlabs.no/team: flais
spec:
  orgId: test.com
  replicas: 1
  port: 80
  image: nginx
  probes:
    readiness:
      path: /readiness
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
